version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: forjustice-postgres
    environment:
      POSTGRES_DB: forjustice
      POSTGRES_USER: forjustice_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forjustice_user -d forjustice"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for job queue
  redis:
    image: redis:7-alpine
    container_name: forjustice-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: forjustice-backend
    ports:
      - "3001:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgresql://forjustice_user:dev_password@postgres:5432/forjustice
      JWT_SECRET: dev-secret-change-in-production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CORS_ORIGIN: http://localhost:3000,http://localhost:19006
      LOG_LEVEL: debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Worker Service
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: forjustice-worker
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://forjustice_user:dev_password@postgres:5432/forjustice
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_LEVEL: debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./worker:/app
      - /app/node_modules
    command: npm run dev

  # Web Frontend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: forjustice-web
    ports:
      - "3000:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: forjustice-network
