on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build backend
        run: |
          cd apps/backend
          npm ci
      - name: Build web
        run: |
          cd apps/web
          npm ci
          npm run build
      - name: Build worker
        run: |
          cd apps/worker
          npm ci
      - name: Docker build & push (backend/web/worker)
        run: echo "Implement docker build/push here"
      - name: Deploy to Google Cloud Run
        run: echo "Implement gcloud run deploy here"